// <auto-generated />
namespace MapsTest4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Addreviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addreviews));
        
        string IMigrationMetadata.Id
        {
            get { return "201301132107242_Add reviews "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
